repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: ^(\.venv|env|venv)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        exclude: ^(\.venv|env|venv)/
        additional_dependencies:
          - types-requests
          - types-redis
        args: ["--ignore-missing-imports", "--disallow-untyped-defs"]
