"""add tables shortLink and linkClick v4

Revision ID: 639db3b1e411
Revises: e229780e7f3d
Create Date: 2025-08-08 15:22:34.644289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639db3b1e411'
down_revision: Union[str, Sequence[str], None] = 'e229780e7f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ShortLinks_id_tag_fkey'), 'ShortLinks', type_='foreignkey')
    op.drop_column('ShortLinks', 'id_tag')
    op.drop_column('ShortLinks', 'custom_domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ShortLinks', sa.Column('custom_domain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ShortLinks', sa.Column('id_tag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ShortLinks_id_tag_fkey'), 'ShortLinks', 'Tags', ['id_tag'], ['id_tag'])
    # ### end Alembic commands ###
