"""delete attributes tokens

Revision ID: 77e961982048
Revises: f6ef5c209e5f
Create Date: 2025-08-07 15:44:11.612046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e961982048'
down_revision: Union[str, Sequence[str], None] = 'f6ef5c209e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'refresh_token')
    op.drop_column('Users', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
