"""add tables shortLink and linkClick v3

Revision ID: e229780e7f3d
Revises: f80b43cc37fa
Create Date: 2025-08-08 12:29:07.394637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e229780e7f3d'
down_revision: Union[str, Sequence[str], None] = 'f80b43cc37fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LinkClicks',
    sa.Column('id_click', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('id_link', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_link'], ['ShortLinks.id_link'], ),
    sa.PrimaryKeyConstraint('id_click')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LinkClicks')
    # ### end Alembic commands ###
