"""add tables shortLink and linkClick

Revision ID: f3c1cda1c0ba
Revises: 77e961982048
Create Date: 2025-08-08 12:24:28.762941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c1cda1c0ba'
down_revision: Union[str, Sequence[str], None] = '77e961982048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
