"""add attribute created_at

Revision ID: f6ef5c209e5f
Revises: e1f9001d0af8
Create Date: 2025-08-07 15:36:41.920794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ef5c209e5f'
down_revision: Union[str, Sequence[str], None] = 'e1f9001d0af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'Users', 'Roles', ['id_role'], ['id_role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'created_at')
    # ### end Alembic commands ###
