"""add tables shortLink and linkClick v2

Revision ID: f80b43cc37fa
Revises: f3c1cda1c0ba
Create Date: 2025-08-08 12:27:35.935182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80b43cc37fa'
down_revision: Union[str, Sequence[str], None] = 'f3c1cda1c0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tags',
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_tag'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ShortLinks',
    sa.Column('id_link', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('custom_domain', sa.String(), nullable=True),
    sa.Column('id_creator', sa.Integer(), nullable=False),
    sa.Column('id_tag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_creator'], ['Users.id_user'], ),
    sa.ForeignKeyConstraint(['id_tag'], ['Tags.id_tag'], ),
    sa.PrimaryKeyConstraint('id_link'),
    sa.UniqueConstraint('short_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ShortLinks')
    op.drop_table('Tags')
    # ### end Alembic commands ###
